sudo: required

services:
  - docker

before_install:
  - docker build -t rs83/doc-react -f Dockerfile.dev .

script:
  - docker run rs83/doc-react npm test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "next-sample"
  env: "docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-690844169827"
  bucket_path: "docker"
  on:
    branch: master
  access_key-id: $Access
  secret_access_key:
    secure : "$Secret"

